DROP TABLE IF EXISTS bigram;
DROP TABLE IF EXISTS word;
DROP TABLE IF EXISTS punctuation;
DROP TABLE IF EXISTS sentence;
DROP TABLE IF EXISTS chapter;
DROP TABLE IF EXISTS paragraph;
DROP TABLE IF EXISTS document;
DROP TABLE IF EXISTS author;
